services:
  heddohon:
    image: zorcererd/heddohon:latest
    container_name: heddohon
    restart: unless-stopped
    ports:
      - '13000:3000'
    volumes:
      - heddohon-data:/data
    env_file: .env

volumes:
  heddohon-data:
